name: Lint, type-check, test and create tag on package version change

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run lint
      - run: npm test
  tag-package-version:
    needs: quality-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: neverendingqs/gh-action-tag-on-npm-version@master
