name: Create tag on package version change

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  tag-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: neverendingqs/gh-action-tag-on-npm-version@master
